language: generic

sudo: false

env:
  global:
    - secure: "VM3yP30pNEnax9xiOG4oT54/o0e/p3OwqUwSMDFDpHrHd0NkeNdbLcG9gMiyb1Vd23T6GElWIlWTllW7jVPFPyS72UnMQHX4KM69TjaabfOr+hsf2yZ5i7CyIAKOXOKeKAY278f5JShO96lUAQCw/7UTI4K6o/scOJlIq/gc3SQ="

before_install:
  # Install miniconda and create TEST env.
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict

install:
  - |
    conda env create --name SEAPY --file environment.yml
    source activate SEAPY
    conda info --all

script:
  - set -e
  - mkdocs build --clean --verbose
  - doctr deploy --built-docs _site .